### ISSUE TITLE
Dashboard crashes with almost every request made.

### ISSUE THREAD

**Issue by JustBeALlama** [ravenclaw900/DietPi-Dashboard#166]
**Describe the bug**:
The dietpi-dashboard process aborts every now and then, not finding a file or directory.

**Version of DietPi-Dashboard**: 0.5.0

**Nightly or stable**: Nightly & Stable

**Version of DietPi**: 5.10.92-v8+

**Device architecture**: Cortex-A53 (ARMv8) 64-bit SoC

**To Reproduce**
1. Run ./dietpi-dashboard.
2. Make a request to the software by clicking a tab in the web dashboard.
3. Software crashes, see error.

**Error log**
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/systemdata.rs:362:34
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted

**Comment by ravenclaw900** [comment]
Hi,
It looks like it's not finding a directory: https://github.com/ravenclaw900/DietPi-Dashboard/blob/686f722da516d916725472f522ae2c70f0fe050c/src/backend/src/systemdata.rs#L362 Does this happen on any page, or just the file browser? Also, unrelated, please update your dashboard to v0.5.1 because of a security vulnerability.

**Comment by JustBeALlama** [comment]
Seems like the issue only happens when i'm browsing the files. I have updated the dashboard to v0.5.1 as you've said.
