### ISSUE TITLE
Terminal auto-login user setting

### ISSUE THREAD

**Issue by Nojwe** [ravenclaw900/DietPi-Dashboard#195]
Running 0.5.1. 

It would be great to be able to set a default user to log into a terminal session instead of defaulting to root. Similar to setting a default user in dietpi.txt at first boot.

**Comment by ravenclaw900** [comment]
I'm wondering what command this would use to start. Maybe something like `su - <user> -s/bin/bash`?

**Comment by MichaIng** [comment]
It could be even `login -f <user>`. `login` used used by `agetty` for regular local console logins as well, btw.

Otherwise, I'd generally prefer `sudo` over `su`. `sudo -su <user>` (`-s -u`) starts with the default shell of the user (when there is no `$SHELL` in environment), `sudo -iu <user>` does the same but with a login shell (sourcing `/etc/profile` etc).
