### ISSUE TITLE
Terminal characters not displaying correctly

### ISSUE THREAD

**Issue by blueyshark** [ravenclaw900/DietPi-Dashboard#559]
In Android 12, using latest version of Mull (based on FF) or Chrome Browser the terminal view displays garbled text. See attached image. When using Firefox/Chrome on desktop (Linux and Windows) the terminal displays correctly.

**Version of DietPi-Dashboard**: 0.6.1

**Nightly or stable**: Stable

**Version of DietPi**: 8.17.2

**Device architecture**: RPi 4 Model B (aarch64)

**To Reproduce**

1. In android, using Mull/Chrome browser, navigate to server page (192.168.X.X:5252)
2. Click on Terminal Tab
3. All text in terminal is garbled, however responsive. See attached image.

**Error log**
No errors

**Additional context**
This might be more to do with Android 12 than the dietpi server?
Thanks for any help.

![signal-2023-05-11-213055_002](https://github.com/ravenclaw900/DietPi-Dashboard/assets/37295856/31908c2d-4044-442c-8c50-e763cbef67c9)

**Comment by blueyshark** [comment]
Yes that's right - when I hit one of the tabs, the overlay rolls over the buttons, with a low opacity gray layer.

**Comment by MichaIng** [comment]
@ravenclaw900 
What do you mean by fingerprint blocking? XSS filter? Nowadays it is actually recommended to actively set the related header to disable XSS filtering competely. Among the few browsers which do still support it (Firefox and Chromium do not) it introduces additional security vulnerabilities while it is questionable whether the ones it theoretically prevents against are still a thing. For modern browsers CSP is anyway used (which we also set) for XSS protection.

I cannot imagine that mobile Chrome does legacy XSS filtering (especially by default), so most likely it is not the iasue here. But since actively disabling it is recommended anyway, we could at least try.

**Comment by ravenclaw900** [comment]
Finally got around to doing some testing: the related setting (at least in my browser) is "Silently block canvas access requests". If you can add an exception for that, the terminal characters should load correctly.

**Comment by ravenclaw900** [comment]
Closing this due to no response. If you still have an issue, please feel free to reopen.

**Comment by blueyshark** [comment]
@ravenclaw900 Hi there, thanks for the help. I think it was more down to the browser, but have since changed phone (and phone operating system) so cannot give you accurate results! But I think you are right, it's the client side rather than the dashboard.
